name: CI - StaffManagement

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - name: Run Unit Tests
        run: dotnet test tests/StaffManagement.UnitTests --no-build --configuration Release --logger "trx;LogFileName=unit.trx" --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: "**/TestResults/*.trx"

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - name: Run Integration Tests
        run: dotnet test tests/StaffManagement.IntegrationTests --no-build --configuration Release --logger "trx;LogFileName=integration.trx" --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: "**/TestResults/*.trx"

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - name: Run E2E Tests
        run: dotnet test tests/StaffManagement.EndToEndTests --no-build --configuration Release --logger "trx;LogFileName=e2e.trx" --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: "**/TestResults/*.trx"
